### ISSUE TITLE
Under active development?

### ISSUE THREAD

**Issue by dominikwilkowski** [typefoo/node-shipping-fedex#12]
Hey there,

I can see the last commit was last year in Oct but I am wondering if you guys are open for PRs? I will jump into development using this lib and the first thing I would contribute is some docs in the README. Some examples and their responses. If you are open  for that, let me know.

**Comment by jjosef** [comment]
Hey @dominikwilkowski,

We are still actively developing this module, however at the current stage it suits our needs. If you want to contribute PR's feel free to!
