### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by vinithhr** [typefoo/node-shipping-fedex#5]
Hi, Don't we face CORS/ Same origin policy issue while FedEx integrating web services from UI?

We are planning to use this plugin, but our study had indicated that we might run into CORS issue when calling webservices of other domain while using JS.

Awaiting for your reply, it will help us to confirm on using this plugin.

Regards,
Vinith.

**Comment by jjosef** [comment]
This module is not a front-end module. You use it on a nodejs server or application
